### ISSUE TITLE
Is there a roadmap?

### ISSUE THREAD

**Issue by AucaCoyan** [LucasOe/tts-external-api#1]
Hello! It's always nice to see an implementation in rust of something existing.
I understand that this may be very beta, but I have some doubts and maybe you can assist me 🛩️ .

- Is there a broad roadmap of features? 
- do you want to add types for the Lua API or XML tags?

thanks you so much!

**Comment by LucasOe** [comment]
Hello Acua! There is currently no roadmap. This project pretty much started as a way for me to learn Rust and some API design, when it comes to implementing features, my limited experience is a major factor. There are two things I have thought about adding:

- an async implementation of the API. Currently I've found no good good way to have an async and synchronous implementation without effectively maintaining two versions of the package.
- deserializing save states from Tabletop Simulator into their own data structs

I'm not quite sure how you would go about adding types for the Lua API or XML tags? If you have any feedback or suggestions feel free to share them! I'm happy to hear them!

**Comment by AucaCoyan** [comment]
Hi!
I see, you went really far with this! Thanks for sharing to the community 😄 . I am currently working on a open source project with less knowledge of rust than you have (I know this because tts-external-api is much greater code than mine!)
As for the things you thought:
* It would be hard to implement both async and sync libraries. I have not heard so far that a library is both async and sync optionally. Normally if you want async you straight look for an alternative
* That sounds great!

About the types of Lua API or XML tags I meant that, currently you have to pass the code of Lua as a string, you don't have intellisense, or any other of language transpilation (I mean transform rust code into lua code). 
[This project](https://github.com/stevenlafl/tts-typescript) is a good sample of what I meant with types. It is based on another library that transpiles typescript to lua.
What are your thoughts about that? Do we really need a library that transpiles rust code to lua code? Is it achievable? Do you have time and interest to walk with the project?

**Comment by LucasOe** [comment]
Transpiling Rust to Lua would be outside of the scope of this project. There are already many other solutions for transpiling to Lua, listed [here](https://github.com/hengestone/lua-languages).

**Comment by AucaCoyan** [comment]
Thanks for the clarification! Have a nice day 😄
